// import Image from 'next/image'
// import { memo } from 'react'
// import CeloIcon from 'src/images/tokens/CELO.svg'
// import PUSOIcon from 'src/images/tokens/PUSO.svg'
// import USDCIcon from 'src/images/tokens/USDC.svg'
// import USDTIcon from 'src/images/tokens/USDT.svg'
// import axlEUROCIcon from 'src/images/tokens/axlEUROC.svg'
// import axlUSDCIcon from 'src/images/tokens/axlUSDC.svg'
// import cCOPIcon from 'src/images/tokens/cCOP.svg'
// import cEURIcon from 'src/images/tokens/cEUR.svg'
// import cGHSIcon from 'src/images/tokens/cGHS.svg'
// import cKESIcon from 'src/images/tokens/cKES.svg'
// import cREALIcon from 'src/images/tokens/cREAL.svg'
// import cUSDIcon from 'src/images/tokens/cUSD.svg'
// import eXOFIcon from 'src/images/tokens/eXOF.svg'
