mutation Adverts_update($input: Advert_UpdateInput!) {
  adverts_update(input: $input) {
    currencyFiat
    currency_crypto
    advertStatus
    duration
    merchant_id
    limitLower
    limitUpper
    tradeType
    rateFixed
    rateFloat
    isFloatRate
  }
}

mutation Adverts_create($input: Advert_CreateInput!) {
  adverts_create(input: $input) {
    rateFixed
    rateFloat
    merchant_id
    isFloatRate
    advertStatus
    limitLower
    limitUpper
    tradeType
    currencyFiat
    currency_crypto
    wallet_address
  }
}

mutation Adverts_delete($input: Advert_DeleteInput!) {
  adverts_delete(input: $input) {
    merchant_id
    rateFixed
    rateFloat
    isFloatRate
    currencyFiat
    currency_crypto
    advertStatus
    duration
    limitLower
    limitUpper
    tradeType
    wallet_address
  }
}

query Adverts_getAll {
  adverts_getAll {
    id
    rateFixed
    rateFloat
    isFloatRate
    advertStatus
    duration
    tradeType
    instructions
    limitLower
    limitUpper
    currencyFiat
    currency_crypto
    wallet_address
    merchant_nickname
    merchant_id
    merchant_trade_count
    wallet_address
    fiatAmountPerCrypto
  }
}

query Adverts_getOne($input: Advert_GetOneInput!) {
  adverts_getOne(input: $input) {
    id
    advertStatus
    duration
    tradeType
    rateFixed
    rateFloat
    isFloatRate
    instructions
    limitLower
    limitUpper
    currencyFiat
    currency_crypto
    wallet_address
    merchant_nickname
    merchant_id
    merchant_trade_count
    wallet_address
    fiatAmountPerCrypto
  }
}

query Adverts_getMerchantAdverts($input: Advert_GetAllInput!) {
  adverts_getMerchantAdverts(input: $input) {
    id
    advertStatus
    duration
    tradeType
    rateFixed
    rateFloat
    isFloatRate
    instructions
    limitLower
    limitUpper
    currencyFiat
    currency_crypto
    wallet_address
    merchant_nickname
    merchant_id
    merchant_trade_count
    wallet_address
    fiatAmountPerCrypto
  }
}
