query static_getTokens {
  static_getTokens {
    name
    address
    decimals
    isBuyable
    isPayable
    symbol
    logoUrl
    chainId
  }
}



query static_getLinks {
  static_getLinks {
    title
    desc
    imgLink
    url
    category
    group
  }
}
